# Generated by Django 4.1.7 on 2023-04-05 01:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_entry_delete_blogmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entry',
            new_name='Post',
        ),
    ]
